### ISSUE TITLE
如果className里面包含了px这两个字符

### ISSUE THREAD

**Issue by lbqdly** [cytle/gulp-pa2rpx#1]
感谢你做了这样一个工具，但我在使用的时候发现，如果className里面包含了px这两个字符，也会被转成rpx。这个能避免吗？

**Comment by cytle** [comment]
可以的，你的具体的类名是什么？

**Comment by cytle** [comment]
现在的正则大概是这样`/([\d\.]+)px/g`，可能匹配了类似`.pxabc`这样的类名。

**Comment by cytle** [comment]
https://github.com/cytle/gulp-px2rpx/commit/1cb8f5b6e5d0ea86edb7d2b8e47d255c3e3b412d

**Comment by cytle** [comment]
已经修复， https://github.com/cytle/gulp-px2rpx/commit/1cb8f5b6e5d0ea86edb7d2b8e47d255c3e3b412d
